python/django/lottoPage/lottoAnalysis/urls.py
from django.urls import path

from . import views

app_name = 'lottoAnalysis'
urlpatterns = [
	#path('', views.index, name='index'),
	path('getStatistics/', views.getStatistics, name='getStatistics'),
	path('home/', views.home, name='home'),
]

python/django/lottoPage/lottoPage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	#path(r'', include('lottoAnalysis.urls')),
    path('lottoAnalysis/', include('lottoAnalysis.urls')),
    path('admin/', admin.site.urls),
]

python/django/lottoPage/lottoAnalysis/models.py
from django.db import models

# Create your models here.

python/django/lottoPage/lottoAnalysis/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.template import loader
#from urllib import request as requestApi
from lottoAnalysis.LottoDataAnal import LottoDataAnal
import json

def home(request) :
	return render(request, 'lottoAnalysis/home.html')

def getStatistics(request) :
	try :
		sDate = request.GET['sDate']
		eDate = request.GET['eDate']
		xAxis = request.GET['xAxis']
		bonus = request.GET['containBonus']
	except (KeyError) :
		return render(request, 'lottoAnalysis/home.html')
	#template = loader.get_template('lottoAnalysis/getStatistics.html')

	lottoDataAnalysys = LottoDataAnal(startDate=sDate, endDate=eDate, isContainSecond=bonus)
	result = lottoDataAnalysys.getDatas(xAxis)
	#result = 0
	context = {
		'result' : result,
	}

	return HttpResponse(json.dumps(context), content_type="application/json")

python/django/lottoPage/lottoAnalysis/templates/lottoAnalysis/getStatistics.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>lotto</title>
        <style>
            .box_big {width:50%; min-width:100px; margin:0px auto; }
            .box_big>div {float:left;}
            .box_big::after {content:'';clear:both;display:block;}
            .box_middle {width:80%;}
            .box_button {width:20%;}
            .box_button>input {height:60px;width:100%}
            .box_middle>ul>li {width:100%;list-style-type:none;margin:10px 20px;}
            .box_middle>ul>li::after {content:'';clear:both;display:block;}
            .box_middle>ul>li>div {float:left;;height:20px; width:40%;margin:10px 20px;}
         
        </style>
    </head>
    <body>
        <h1> ahaha </h1>

        <form id='loadStatistics' action="{% url 'lottoAnalysis:getStatistics' %}" method="post">
            {% csrf_token %} 
            <div class='box_big'>
                <div class='box_middle'>
                    <ul>
                        <li>
                            <div>
                               시작일: <input type='date'>
                            </div>
                            <div>
                               종료일: <input type='date'>
                            </div>
                        </li>
                        
                        <li>
                            <div>
                                보너스번호 포함여부: 
                                <select>
                                    <option value='0'> 미포함</option>
                                    <option value='1'> 포함</option>
                                </select>
                            </div>
                            <div>
                                x축 설정: 
                                <select>
                                    <option value='0'> 최소값</option>
                                    <option value='1'> 최대값</option>
                                </select>
                            
                            </div>
                        </li>
                    </ul>
                </div>
                
                <div class='box_button'>
                    <input type='button' value='abcd'>
                </div>
            </div>
        
        </form>
    </body>
</html>

#{% for pa in pa_list %}
#{% endfor %}
#{{ forloop.counter }}

python/django/lottoPage/lottoAnalysis/templates/lottoAnalysis/home.html
{% load static %}

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>lotto</title>
        <style></style>
        <link rel='stylesheet' type='text/css' href='{% static 'lottoAnalysis/css/style.css' %}' >
        <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' integrity='sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T' crossorigin='anonymous' >
        <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css' >
        <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js'></script >
        <script src='https://code.jquery.com/jquery-1.12.4.min.js' integrity='sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=' crossorigin='anonymous'></script>
        <script src='https://cdn.jsdelivr.net/npm/pikaday/pikaday.js'></script>
        <script>
            $(document).ready(function(){
                initDate();
               
                $("#searchBtn").click(function(){
                    getDatas();
                });
            });
            function getDatas(){
                
                var sDate = $("#sDate").val() || '';
                var eDate = $("#eDate").val() || '';
                var containBonus = $("#containBonus").val();
                var xAxis = $("#xAxis").val();
                var datas = JSON.stringify({'sDate': sDate, 'eDate': eDate, 'containBonus': containBonus, 'xAxis': xAxis, 'csrfmiddlewaretoken': '{{ csrf_token }}'})    
                console.log(datas);
                $.ajax({
                    type:"GET",
                    url:"{% url 'lottoAnalysis:getStatistics' %}",
                    data:datas,
                    dataType:'json',
                    traditional: true,
                    async: false,
                    contentType: 'application/json',
                    success:function(data){
                        makeChart(data.result);
                    },
                    error:function(err){
                            alert("안됀다야::::"+err);
                            
                    }
                });
                

            
            }

            function initDate(){
                
                var sPicker = new Pikaday({
                    field: document.getElementById('sDate'),
                    format: 'YYYY-MM-DD',
                    toString(date, format) {
                        // you should do formatting based on the passed format,
                        // but we will just return 'D/M/YYYY' for simplicity
                        const day = date.getDate();
                        const month = date.getMonth() + 1;
                        const year = date.getFullYear();
                        return `${year}-${month}-${day}`;
                    },
                    parse(dateString, format) {
                        // dateString is the result of `toString` method
                        const parts = dateString.split('/');
                        const day = parseInt(parts[0], 10);
                        const month = parseInt(parts[1], 10) - 1;
                        const year = parseInt(parts[2], 10);
                        return new Date(year, month, day);
                    }
                });
                
                
                var ePicker = new Pikaday({
                    field: document.getElementById('eDate'),
                    format: 'YYYY-MM-DD',
                    toString(date, format) {
                        // you should do formatting based on the passed format,
                        // but we will just return 'D/M/YYYY' for simplicity
                        const day = date.getDate();
                        const month = date.getMonth() + 1;
                        const year = date.getFullYear();
                        return `${year}-${month}-${day}`;
                    },
                    parse(dateString, format) {
                        // dateString is the result of `toString` method
                        const parts = dateString.split('/');
                        const day = parseInt(parts[0], 10);
                        const month = parseInt(parts[1], 10) - 1;
                        const year = parseInt(parts[2], 10);
                        return new Date(year, month, day);
                    }
                });


            }

            function makeChart(result){
                var ctx = document.getElementById("myChart").getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'scatter',
                    data: {
                        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
                        datasets: [{
                            label: '# of Votes',
                            data: result,
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            borderColor: [
                                'rgba(255,99,132,1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero:true
                                }
                            }]
                        }
                    }
                });
            }
        
        </script>
    </head>
    <body>
        
        <form id='loadStatistics' action="{% url 'lottoAnalysis:getStatistics' %}" method="post">
            {% csrf_token %} 
            <div class='box_big'>
                <div class='box_middle'>
                    <ul>
                        <li>
                            <div>
                                <div class='leftOrder'>시작일: </div>
                                <div class='rightOrder'>
                                    <input type='text' id='sDate' readonly>
                                </div>
                            </div>
                            <div>
                                <div class='leftOrder'>종료일: </div>
                                <div class='rightOrder'>
                                    <input type='text' id='eDate' readonly>
                                </div>
                            </div>
                        </li>
                        
                        <li>
                            <div>
                                <div class='leftOrder'> 보너스번호 포함여부:</div> 
                                <div class='rightOrder'>
                                    <select id='containBonus'>
                                        <option value='0' selected> 미포함</option>
                                        <option value='1'> 포함</option>
                                    </select>
                                </div>
                            </div>
                            <div>
                                <div class='leftOrder'>x축 설정:</div>
                                <div class='rightOrder'> 
                                    <select id='xAxis'>
                                        <option value='0' selected> 최소값</option>
                                        <option value='1'> 최대값</option>
                                    </select>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                
                <div class='box_button'>
                   <button id='searchBtn' type="button" class="btn btn-light">검색</button>
                </div>
            </div>
        
        </form>

        
        <div class="chart-container" style="">
            <canvas id="myChart"></canvas>
        </div>



            
    </body>
</html>

python/django/lottoPage/lottoAnalysis/templates/lottoAnalysis/index.html
<h1> index </h1>


#{% for pa in pa_list %}
#{% endfor %}
#{{ forloop.counter }}